const FALLBACK_FIXTURE={entities:[{urn:'urn:li:dataset:(urn:li:dataPlatform:snowflake,commerce.public.customers,PROD)',name:'customers',platform:'Snowflake',owner:'data-platform',tags:['PII','Tier1'],fields:[{name:'customer_id',type:'VARCHAR',nullable:false},{name:'email',type:'VARCHAR',nullable:false,tags:['PII']},{name:'customer_tier',type:'VARCHAR',nullable:true},{name:'legacy_segment',type:'VARCHAR',nullable:true,deprecated:true}],queries:['select customer_id, email from commerce.public.customers where email is not null','select customer_tier, count(*) from commerce.public.customers group by 1'],downstream:['stg_customers','dim_customers','marketing_audience']},{urn:'urn:li:dataset:(urn:li:dataPlatform:snowflake,commerce.public.orders,PROD)',name:'orders',platform:'Snowflake',owner:'finance-data',tags:['Tier1'],fields:[{name:'order_id',type:'VARCHAR',nullable:false},{name:'customer_id',type:'VARCHAR',nullable:false},{name:'total_amount',type:'BIGINT',nullable:false,description:'Amount in integer cents'}],queries:['select sum(total_amount)/100.0 as revenue from commerce.public.orders'],downstream:['fct_orders','revenue_daily','executive_revenue_dashboard']}]};
let fixture=FALLBACK_FIXTURE,artifacts={},active='sql',lastSelection=null,lastHigh=false,guideStep=-1,voiceOn=false;
const requestEl=document.getElementById('request'),output=document.getElementById('output'),ctx=document.getElementById('contextCards'),risk=document.getElementById('riskBadge'),approve=document.getElementById('approve'),generateBtn=document.getElementById('generate');
const reportPanel=document.getElementById('reportPanel'),guideDock=document.getElementById('guideDock'),guideText=document.getElementById('guideText'),guideStepLabel=document.getElementById('guideStepLabel'),guideStart=document.getElementById('guideStart'),guideNext=document.getElementById('guideNext'),guideBack=document.getElementById('guideBack'),guideVoice=document.getElementById('guideVoice'),guideClose=document.getElementById('guideClose');
renderContext(null);
fetch('fixtures/datahub-context.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`fixture HTTP ${r.status}`);return r.json()}).then(j=>{if(j&&Array.isArray(j.entities)&&j.entities.length>=2)fixture=j}).catch(err=>console.warn('ContextForge fixture fallback active:',err));

document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{requestEl.value=b.dataset.preset;resetRun()});
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');active=b.dataset.tab;renderArtifact()});
generateBtn.onclick=performAnalysis;
approve.onclick=()=>{approveRun();if(guideStep===4){guideStep=5;renderGuide()}};
document.getElementById('downloadReport').onclick=downloadRunReport;

guideStart.onclick=startGuide;
guideNext.onclick=()=>{if(guideStep<5){guideStep++;renderGuide()}};
guideBack.onclick=()=>{if(guideStep>0){guideStep--;renderGuide()}};
guideVoice.onclick=()=>{voiceOn=!voiceOn;guideVoice.textContent=voiceOn?'🔊':'🔇';guideVoice.setAttribute('aria-pressed',String(voiceOn));if(!voiceOn&&'speechSynthesis'in window)window.speechSynthesis.cancel();if(voiceOn&&guideStep>=0)speak(getGuideStep(guideStep).text)};
guideClose.onclick=closeGuide;

function startGuide(){guideStep=0;resetRun();guideDock.hidden=false;document.body.classList.add('guide-active');guideStart.textContent='Restart guided demo';renderGuide()}
function closeGuide(){guideStep=-1;guideDock.hidden=true;document.body.classList.remove('guide-active');clearSpotlights();if('speechSynthesis'in window)window.speechSynthesis.cancel()}

function getGuideStep(step){const downstream=lastSelection?.entity?.downstream?.length||3;return [
{target:'hero',label:'INTRO',action:'Next',text:'ContextForge starts with context before code. It grounds a requested data change in DataHub metadata before generating anything.'},
{target:'requestPanel',label:'REQUEST',action:'Analyze',text:'This change renames a governed customer email field. The next step analyzes the DataHub graph before code is generated.'},
{target:'contextPanel',label:'EVIDENCE',action:'View artifacts',text:`Analysis complete. ContextForge found schema, lineage, ownership, governance and usage evidence, including ${downstream} downstream assets.`},
{target:'resultPanel',label:'ARTIFACTS',action:'Review gate',text:'The system generated a dbt migration, schema tests and an evidence-linked PR summary. High-impact changes stay behind a human gate.'},
{target:'resultPanel',label:'HUMAN GATE',action:'Approve artifact',text:'This governed change is not auto-merged. Review the evidence, then approve the artifact to mark it ready for a pull request.'},
{target:'reportPanel',label:'COMPLETE',action:'Restart demo',text:'Run complete. The report captures the request, DataHub evidence, generated artifacts, impact decision and final approval status.'}
][step]}

function renderGuide(){const s=getGuideStep(guideStep);if(!s)return;guideStepLabel.textContent=`Step ${guideStep+1} of 6 • ${s.label}`;guideText.textContent=s.text;guideBack.disabled=guideStep===0;guideNext.disabled=false;guideNext.textContent=s.action;clearSpotlights();const target=document.getElementById(s.target);if(target){target.classList.add('spotlight');setTimeout(()=>target.scrollIntoView({behavior:'smooth',block:guideStep===4?'end':'center'}),80)}
if(guideStep===1){guideNext.onclick=()=>{performAnalysis();guideStep=2;setTimeout(renderGuide,220)}}else if(guideStep===2){guideNext.onclick=()=>{active='pr';document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab==='pr'));renderArtifact();guideStep=3;renderGuide()}}else if(guideStep===3){guideNext.onclick=()=>{guideStep=4;renderGuide()}}else if(guideStep===4){guideNext.onclick=()=>{if(!approve.disabled){approveRun();guideStep=5;renderGuide()}}}else if(guideStep===5){guideNext.onclick=startGuide}else{guideNext.onclick=()=>{guideStep++;renderGuide()}}
if(voiceOn)speak(s.text)}

function speak(text){if(!voiceOn||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.96;u.pitch=1;u.volume=.9;window.speechSynthesis.speak(u)}

function resetRun(){artifacts={};lastSelection=null;lastHigh=false;active='sql';renderContext(null);risk.textContent='WAITING';risk.style.color='';approve.disabled=true;approve.textContent='Approve artifact';output.textContent='Run an analysis to generate artifacts.';reportPanel.hidden=true;document.querySelectorAll('.tab').forEach((x,i)=>x.classList.toggle('active',i===0))}
function resolveSelection(){const q=(requestEl.value||'').trim().toLowerCase();const entity=q.includes('order')||q.includes('amount')||q.includes('revenue')?fixture.entities[1]:fixture.entities[0];const isType=q.includes('amount')||q.includes('decimal')||q.includes('dollar');let field;if(isType)field=entity.fields.find(f=>f.name==='total_amount');else if(q.includes('legacy_segment')||q.includes('deprecat'))field=entity.fields.find(f=>f.name==='legacy_segment');else field=entity.fields.find(f=>f.name==='email')||entity.fields[0];return {q,entity,field,isType}}
function performAnalysis(){try{generateBtn.disabled=true;generateBtn.textContent='Analyzing metadata context…';const {q,entity,field,isType}=resolveSelection();if(!entity||!field)throw new Error('Unable to resolve target asset from available DataHub context.');const high=(field.tags||[]).includes('PII')||(entity.tags||[]).includes('Tier1');lastSelection={entity,field,isType,q};lastHigh=high;renderContext({entity,field});artifacts=generate(entity,field,{isType,q});risk.textContent=high?'HIGH IMPACT • REVIEW REQUIRED':'MEDIUM IMPACT';risk.style.color=high?'#ff9c9c':'#ffcc66';approve.disabled=false;approve.textContent='Approve artifact';renderArtifact();reportPanel.hidden=true}catch(err){console.error(err);risk.textContent='ANALYSIS ERROR';risk.style.color='#ff9c9c';output.textContent=`ContextForge could not complete analysis: ${err.message}`}finally{generateBtn.disabled=false;generateBtn.textContent='Analyze DataHub context & generate patch'}}
function approveRun(){approve.textContent='APPROVED — ready for PR';approve.disabled=true;renderRunReport()}
function renderRunReport(){if(!lastSelection)return;const {entity,field}=lastSelection;document.getElementById('reportRequest').textContent=requestEl.value.trim();document.getElementById('reportImpact').textContent=lastHigh?'HIGH — governed change with downstream dependencies':'MEDIUM — review recommended';document.getElementById('reportEvidence').innerHTML=`<li>✓ Schema: ${entity.name}.${field.name} • ${field.type}</li><li>✓ Lineage: ${entity.downstream.length} downstream assets</li><li>✓ Ownership: ${entity.owner}</li><li>✓ Governance: ${[...new Set([...(entity.tags||[]),...(field.tags||[])])].join(', ')||'No tags'}</li><li>✓ Usage: ${entity.queries.length} observed query pattern(s)</li>`;document.getElementById('reportDecision').textContent=lastHigh?'High-impact governed change. Human approval was required before the artifact could be marked ready for PR.':'Change reviewed and approved before PR readiness.';reportPanel.hidden=false}
function renderContext(sel){ctx.innerHTML='';const governance=sel?[...new Set([...(sel.entity.tags||[]),...(sel.field.tags||[])])].join(', ')||'No tags':'';const cards=sel?[['Schema',`${sel.entity.name}.${sel.field.name} • ${sel.field.type} • ${sel.field.nullable?'nullable':'required'}`],['Lineage',`${sel.entity.downstream.length} downstream assets: ${sel.entity.downstream.join(', ')}`],['Ownership',`${sel.entity.owner} owns this ${sel.entity.platform} dataset`],['Governance',governance],['Usage',`${sel.entity.queries.length} observed query pattern(s) inform generated compatibility logic`]]:[['Schema','Waiting for change request'],['Lineage','Waiting for target asset'],['Ownership','Waiting for DataHub context'],['Governance','Waiting for trust signals'],['Usage','Waiting for query evidence']];cards.forEach(([k,v])=>ctx.innerHTML+=`<div class="context-card"><b>${k}</b><span>${v}</span></div>`)}
function generate(e,f,o){if(o.isType){return {sql:`-- ContextForge generated dbt migration\n-- Grounded in DataHub: ${e.urn}\n\nwith source as (\n  select\n    order_id,\n    customer_id,\n    cast(total_amount as decimal(18,2)) / 100.0 as total_amount_dollars\n  from {{ source('commerce', 'orders') }}\n)\nselect * from source;`,yaml:`version: 2\nmodels:\n  - name: stg_orders\n    columns:\n      - name: total_amount_dollars\n        description: "Order amount normalized from integer cents using DataHub usage evidence."\n        tests:\n          - not_null`,pr:`## ContextForge impact-aware migration\n\n**DataHub evidence**\n- Owner: ${e.owner}\n- Downstream: ${e.downstream.join(', ')}\n- Observed query: \`${e.queries[0]}\`\n\n**Change**\nIntroduce \`total_amount_dollars DECIMAL(18,2)\` while preserving the source cents field during migration.\n\n**Risk gate**\nTier1 dataset — human review required before merge.`};}if(f.name==='legacy_segment'){return {sql:`-- ContextForge generated deprecation migration\nselect\n  customer_id,\n  email,\n  customer_tier,\n  customer_tier as legacy_segment -- temporary compatibility alias\nfrom {{ source('commerce', 'customers') }};`,yaml:`version: 2\nmodels:\n  - name: stg_customers\n    columns:\n      - name: legacy_segment\n        description: "DEPRECATED compatibility alias pending downstream migration."`,pr:`## ContextForge deprecation plan\n\n**DataHub evidence**\n- Field: \`${e.name}.${f.name}\` is marked deprecated\n- Owner: ${e.owner}\n- Downstream assets: ${e.downstream.join(', ')}\n\n**Human gate**\nTier1 change — approval required before merge.`};}return {sql:`-- ContextForge generated dbt compatibility migration\n-- DataHub says ${e.name}.${f.name} is PII and feeds ${e.downstream.length} downstream assets.\n\nwith source as (\n  select\n    customer_id,\n    email as primary_email,\n    email as email, -- temporary compatibility alias\n    customer_tier\n  from {{ source('commerce', 'customers') }}\n)\nselect * from source;`,yaml:`version: 2\nmodels:\n  - name: stg_customers\n    columns:\n      - name: primary_email\n        meta:\n          datahub_tags: [PII]\n        tests:\n          - not_null\n      - name: email\n        description: "DEPRECATED compatibility alias."`,pr:`## ContextForge impact-aware rename\n\n**DataHub evidence**\n- Schema: \`${e.name}.${f.name} ${f.type}\`\n- Governance: PII, Tier1\n- Owner: ${e.owner}\n- Downstream assets: ${e.downstream.join(', ')}\n- Usage pattern: \`${e.queries[0]}\`\n\n**Generated migration**\nAdd \`primary_email\` while retaining \`email\` as a temporary compatibility alias. Preserve PII classification and migrate downstream consumers before alias removal.\n\n**Human gate**\nHigh-impact PII change: approval required before PR merge.\n\n**DataHub write-back plan**\nAfter approval, save the migration decision to DataHub so future agents inherit the rationale.`}}
function renderArtifact(){output.textContent=artifacts[active]||'Run an analysis to generate artifacts.'}
function clearSpotlights(){document.querySelectorAll('.spotlight').forEach(x=>x.classList.remove('spotlight'))}
function buildReportMarkdown(){if(!lastSelection)return'';const {entity,field}=lastSelection;const governance=[...new Set([...(entity.tags||[]),...(field.tags||[])])].join(', ')||'No tags';return `# ContextForge Run Report\n\n## Requested change\n${requestEl.value.trim()}\n\n## DataHub evidence analyzed\n- Schema: ${entity.name}.${field.name} • ${field.type}\n- Lineage: ${entity.downstream.length} downstream assets — ${entity.downstream.join(', ')}\n- Ownership: ${entity.owner}\n- Governance: ${governance}\n- Usage: ${entity.queries.length} observed query pattern(s)\n\n## Impact\n${lastHigh?'HIGH — governed change with downstream dependencies':'MEDIUM — review recommended'}\n\n## Artifacts generated\n- dbt compatibility migration\n- schema tests\n- evidence-linked PR summary\n\n## Final status\nAPPROVED — READY FOR PR\n\n## Write-back status\nPlanned after approval. This clean-room demo does not execute a live DataHub write-back or merge a pull request.\n`}
function downloadRunReport(){const text=buildReportMarkdown();if(!text)return;const blob=new Blob([text],{type:'text/markdown'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='contextforge-run-report.md';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
