const FALLBACK_FIXTURE={entities:[{urn:'urn:li:dataset:(urn:li:dataPlatform:snowflake,commerce.public.customers,PROD)',name:'customers',platform:'Snowflake',owner:'data-platform',tags:['PII','Tier1'],fields:[{name:'customer_id',type:'VARCHAR',nullable:false},{name:'email',type:'VARCHAR',nullable:false,tags:['PII']},{name:'customer_tier',type:'VARCHAR',nullable:true},{name:'legacy_segment',type:'VARCHAR',nullable:true,deprecated:true}],queries:['select customer_id, email from commerce.public.customers where email is not null','select customer_tier, count(*) from commerce.public.customers group by 1'],downstream:['stg_customers','dim_customers','marketing_audience']},{urn:'urn:li:dataset:(urn:li:dataPlatform:snowflake,commerce.public.orders,PROD)',name:'orders',platform:'Snowflake',owner:'finance-data',tags:['Tier1'],fields:[{name:'order_id',type:'VARCHAR',nullable:false},{name:'customer_id',type:'VARCHAR',nullable:false},{name:'total_amount',type:'BIGINT',nullable:false}],queries:['select sum(total_amount)/100.0 as revenue from commerce.public.orders'],downstream:['fct_orders','revenue_daily','executive_revenue_dashboard']}]};
let fixture=FALLBACK_FIXTURE,artifacts={},active='sql',lastSelection=null,lastHigh=false,guideStep=-1,voiceOn=false;
const $=id=>document.getElementById(id),requestEl=$('request'),output=$('output'),ctx=$('contextCards'),risk=$('riskBadge'),gate=$('gateBadge'),trace=$('decisionTrace'),approve=$('approve'),reportPanel=$('reportPanel'),memoryPanel=$('memoryPanel'),guideDock=$('guideDock'),guideText=$('guideText'),guideStepLabel=$('guideStepLabel'),guideNext=$('guideNext'),guideBack=$('guideBack'),guideVoice=$('guideVoice');
fetch('fixtures/datahub-context.json',{cache:'no-store'}).then(r=>r.ok?r.json():Promise.reject()).then(j=>{if(j?.entities?.length>=2)fixture=j}).catch(()=>{});renderContext(null);renderTrace(null);
const presets=[...document.querySelectorAll('[data-preset]')];presets.forEach(b=>b.onclick=()=>{requestEl.value=b.dataset.preset;setPreset(b);resetRun(false)});document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>selectArtifact(b.dataset.tab));$('generate').onclick=performAnalysis;approve.onclick=approveRun;$('downloadReport').onclick=downloadReport;$('followup').onclick=runMemoryFollowup;$('guideStart').onclick=startGuide;guideBack.onclick=()=>{if(guideStep>0){guideStep--;renderGuide()}};$('guideClose').onclick=closeGuide;guideVoice.onclick=()=>{voiceOn=!voiceOn;guideVoice.textContent=voiceOn?'🔊':'🔇';if(!voiceOn&&'speechSynthesis'in window)speechSynthesis.cancel();if(voiceOn)speak(getStep(guideStep).text)};
function setPreset(b){presets.forEach(x=>x.classList.toggle('active',x===b))}function choosePreset(i){const b=presets[i];requestEl.value=b.dataset.preset;setPreset(b)}function selectArtifact(n){active=n;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===n));renderArtifact()}
function resetRun(clear=true){artifacts={};active='sql';lastSelection=null;lastHigh=false;renderContext(null);renderTrace(null);risk.textContent=gate.textContent='WAITING';approve.disabled=true;approve.textContent='Approve artifact';output.textContent='Run an analysis to generate artifacts.';reportPanel.hidden=true;memoryPanel.hidden=true;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab==='sql'));if(clear)presets.forEach(x=>x.classList.remove('active'))}
function resolve(){const q=requestEl.value.trim().toLowerCase(),entity=q.includes('order')||q.includes('amount')||q.includes('revenue')?fixture.entities[1]:fixture.entities[0],isType=q.includes('amount')||q.includes('decimal')||q.includes('dollar'),isDep=q.includes('legacy_segment')||q.includes('deprecat'),field=isType?entity.fields.find(f=>f.name==='total_amount'):isDep?entity.fields.find(f=>f.name==='legacy_segment'):entity.fields.find(f=>f.name==='email');return{q,entity,field,isType,isDep}}
function performAnalysis(){const {q,entity,field,isType,isDep}=resolve();if(!entity||!field)return;lastSelection={q,entity,field,isType,isDep};lastHigh=(field.tags||[]).includes('PII')||(entity.tags||[]).includes('Tier1');renderContext(lastSelection);renderTrace(lastSelection);artifacts=generate(entity,field,{q,isType,isDep});risk.textContent=lastHigh?'HIGH IMPACT • REVIEW REQUIRED':'MEDIUM IMPACT';gate.textContent=lastHigh?'HUMAN APPROVAL':'REVIEW';approve.disabled=false;approve.textContent='Approve artifact';renderArtifact();reportPanel.hidden=true;memoryPanel.hidden=true}
function renderContext(sel){ctx.innerHTML='';const cards=sel?[['Schema',`${sel.entity.name}.${sel.field.name} • ${sel.field.type||'UNKNOWN'} • ${sel.field.nullable?'nullable':'required'}`],['Lineage',`${sel.entity.downstream.length} downstream assets: ${sel.entity.downstream.join(', ')}`],['Ownership',`${sel.entity.owner} owns this ${sel.entity.platform} dataset`],['Governance',[...new Set([...(sel.entity.tags||[]),...(sel.field.tags||[])])].join(', ')||'No tags'],['Usage',`${sel.entity.queries.length} observed query pattern(s) inform compatibility logic`]]:[['Schema','Waiting for change request'],['Lineage','Waiting for target asset'],['Ownership','Waiting for DataHub context'],['Governance','Waiting for trust signals'],['Usage','Waiting for query evidence']];cards.forEach(([k,v])=>ctx.innerHTML+=`<div class="context-card"><b>${k}</b><span>${v}</span></div>`)}
function renderTrace(sel){if(!sel){trace.innerHTML='<article><small>EVIDENCE</small><strong>Waiting for DataHub context</strong></article><article><small>IMPACT</small><strong>Not classified</strong></article><article><small>POLICY</small><strong>No policy selected</strong></article><article><small>SAFETY GATE</small><strong>No action authorized</strong></article>';return}const policy=sel.isType?'Preserve source units; introduce normalized decimal; validate revenue':sel.isDep?'Retain compatibility alias; migrate consumers; require review':'Preserve PII classification; retain compatibility alias; migrate consumers';trace.innerHTML=`<article><small>EVIDENCE</small><strong>5 context signals • ${sel.entity.downstream.length} downstream assets</strong></article><article><small>IMPACT</small><strong>${lastHigh?'HIGH — governed / Tier1 blast radius':'MEDIUM'}</strong></article><article><small>POLICY</small><strong>${policy}</strong></article><article><small>SAFETY GATE</small><strong>${lastHigh?'GENERATE + REQUIRE HUMAN APPROVAL':'GENERATE + REVIEW'}</strong></article>`}
function generate(e,f,o){if(o.isType)return{sql:`-- ContextForge type-safe migration\nselect order_id, customer_id,\n  cast(total_amount as decimal(18,2))/100.0 as total_amount_dollars\nfrom {{ source('commerce','orders') }};`,yaml:`version: 2\nmodels:\n  - name: stg_orders\n    columns:\n      - name: total_amount_dollars\n        description: "Normalized from integer cents using DataHub usage evidence."\n        tests: [not_null]`,pr:`## Impact-aware type migration\n- Owner: ${e.owner}\n- Downstream: ${e.downstream.join(', ')}\n- Usage evidence preserves revenue-unit semantics\n\n**Safety Gate:** Tier1 change requires human approval.`};if(o.isDep)return{sql:`-- ContextForge deprecation migration\nselect customer_id, email, customer_tier,\n  customer_tier as legacy_segment -- temporary compatibility alias\nfrom {{ source('commerce','customers') }};`,yaml:`version: 2\nmodels:\n  - name: stg_customers\n    columns:\n      - name: legacy_segment\n        description: "DEPRECATED compatibility alias pending downstream migration."`,pr:`## Governed deprecation plan\n- Field: ${e.name}.${f.name}\n- Owner: ${e.owner}\n- Downstream: ${e.downstream.join(', ')}\n\nKeep compatibility alias until downstream migration is verified. Human approval required.`};return{sql:`-- ContextForge PII-safe rename\nselect customer_id, email as primary_email, email as email, customer_tier\nfrom {{ source('commerce','customers') }};`,yaml:`version: 2\nmodels:\n  - name: stg_customers\n    columns:\n      - name: primary_email\n        meta: {datahub_tags: [PII]}\n        tests: [not_null]\n      - name: email\n        description: "DEPRECATED compatibility alias."`,pr:`## Impact-aware PII rename\n- Governance: PII, Tier1\n- Owner: ${e.owner}\n- Downstream: ${e.downstream.join(', ')}\n\nPreserve classification and compatibility until consumers migrate. Human approval required.`}}
function renderArtifact(){output.textContent=artifacts[active]||'Run an analysis to generate artifacts.'}
function approveRun(){if(!lastSelection)return;approve.textContent='APPROVED — ready for PR';approve.disabled=true;const r={request:requestEl.value.trim(),entity:lastSelection.entity.name,field:lastSelection.field.name,downstream:lastSelection.entity.downstream,decision:'APPROVED',policy:trace.textContent,ts:new Date().toISOString()};localStorage.setItem('contextforge.lastDecision',JSON.stringify(r));renderReport()}
function renderReport(){const {entity,field}=lastSelection;$('reportRequest').textContent=requestEl.value.trim();$('reportImpact').textContent='HIGH — governed change with downstream dependencies';$('reportEvidence').innerHTML=`<li>✓ Schema: ${entity.name}.${field.name} • ${field.type}</li><li>✓ Lineage: ${entity.downstream.length} downstream assets</li><li>✓ Ownership: ${entity.owner}</li><li>✓ Governance: ${[...new Set([...(entity.tags||[]),...(field.tags||[])])].join(', ')}</li><li>✓ Usage: ${entity.queries.length} observed query pattern(s)</li>`;$('reportDecision').textContent='Safety Gate required human approval before the generated artifacts could be marked ready for PR.';$('memoryStatus').textContent='Approved decision retained in browser demo memory. Live DataHub write-back is deliberately not faked in the browser.';reportPanel.hidden=false}
function runMemoryFollowup(){const prior=JSON.parse(localStorage.getItem('contextforge.lastDecision')||'null');memoryPanel.hidden=false;if(prior){memoryPanel.querySelector('.memory-callout p').innerHTML=`ContextForge retained the approved decision for <code>${prior.field}</code> and its ${prior.downstream.length} downstream consumers. A destructive follow-up is blocked until migration verification exists.`}setTimeout(()=>memoryPanel.scrollIntoView({behavior:'smooth',block:'center'}),80)}
function buildReport(){if(!lastSelection)return'';const e=lastSelection.entity,f=lastSelection.field;return`# ContextForge Run Report\n\n## Request\n${requestEl.value.trim()}\n\n## DataHub evidence\n- Schema: ${e.name}.${f.name} • ${f.type}\n- Lineage: ${e.downstream.join(', ')}\n- Owner: ${e.owner}\n- Governance: ${[...new Set([...(e.tags||[]),...(f.tags||[])])].join(', ')}\n- Usage: ${e.queries.length} observed query patterns\n\n## Decision\nHIGH IMPACT — HUMAN APPROVAL REQUIRED\n\n## Artifacts\n- dbt migration\n- schema tests\n- evidence-linked PR summary\n\n## Final status\nAPPROVED — READY FOR PR\n\n## Context memory\nBrowser demo retained the approved decision locally. Live DataHub write-back requires configured credentials and an approved metadata mutation.\n`}
function downloadReport(){const blob=new Blob([buildReport()],{type:'text/markdown'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='contextforge-run-report.md';a.click();URL.revokeObjectURL(url)}
function startGuide(){guideStep=0;choosePreset(0);resetRun(false);guideDock.hidden=false;document.body.classList.add('guide-active');renderGuide()}function closeGuide(){guideStep=-1;guideDock.hidden=true;document.body.classList.remove('guide-active');clearSpotlights();if('speechSynthesis'in window)speechSynthesis.cancel()}
function getStep(s){const d=lastSelection?.entity?.downstream?.length||3;return[
{target:'painStrip',label:'WHY',action:'Show scenarios',text:'Prompt-only agents can generate valid code and still break production. ContextForge adds organizational context and an authorization boundary.'},
{target:'requestPanel',label:'BREADTH',action:'Type migration',text:'Three change classes prove this is not one canned rename: PII rename, type migration, and deprecation.'},
{target:'requestPanel',label:'TYPE',action:'Deprecation',text:'A type migration can silently change business meaning. ContextForge uses usage and lineage to preserve semantics.'},
{target:'requestPanel',label:'DEPRECATION',action:'Analyze',text:'Deprecation is a different failure mode. We will run it end-to-end.'},
{target:'contextPanel',label:'CONTEXT',action:'Decision trace',text:`DataHub supplies schema, lineage, ownership, governance and usage. This run sees ${d} downstream assets before generation.`},
{target:'decisionPanel',label:'POLICY',action:'dbt model',text:'Context becomes a compact decision trace: evidence, impact, policy and Safety Gate outcome. This is an auditable summary, not hidden chain-of-thought.'},
{target:'resultPanel',label:'MODEL',action:'Schema tests',text:'Artifact one is a compatibility-aware dbt migration grounded in the metadata evidence.'},
{target:'resultPanel',label:'TESTS',action:'PR summary',text:'Artifact two turns the policy into schema documentation and tests.'},
{target:'resultPanel',label:'PR + GATE',action:'Approve',text:'Artifact three explains the blast radius. Because the asset is Tier1, the Safety Gate refuses silent autonomous merge.'},
{target:'reportPanel',label:'AUDIT',action:'Context memory',text:'Approval creates a run report and retains the decision so future work can inherit what was already learned.'},
{target:'memoryPanel',label:'MEMORY',action:'Why it matters',text:'The follow-up demonstrates organizational memory: destructive removal is blocked because downstream migration verification is still missing.'},
{target:'architecture',label:'VALUE',action:'Expansion',text:'ContextForge turns DataHub into a context and control layer around coding agents: know blast radius, carry governance into code, and keep decisions auditable.'},
{target:'expansion',label:'PLATFORM',action:'Restart',text:'Data engineering is the proving ground. The same governed-change pattern can extend to cyber and live game systems without changing this hackathon focus.'}
][s]}
function renderGuide(){const s=getStep(guideStep);if(!s)return;guideStepLabel.textContent=`Step ${guideStep+1} of 13 • ${s.label}`;guideText.textContent=s.text;guideBack.disabled=guideStep===0;guideNext.textContent=s.action;clearSpotlights();const t=$(s.target);if(t){t.classList.add('spotlight');setTimeout(()=>t.scrollIntoView({behavior:'smooth',block:guideStep===8?'end':'center'}),80)}const actions=[()=>{guideStep=1;renderGuide()},()=>{choosePreset(1);guideStep=2;renderGuide()},()=>{choosePreset(2);guideStep=3;renderGuide()},()=>{performAnalysis();guideStep=4;setTimeout(renderGuide,120)},()=>{guideStep=5;renderGuide()},()=>{selectArtifact('sql');guideStep=6;renderGuide()},()=>{selectArtifact('yaml');guideStep=7;renderGuide()},()=>{selectArtifact('pr');guideStep=8;renderGuide()},()=>{approveRun();guideStep=9;renderGuide()},()=>{runMemoryFollowup();guideStep=10;setTimeout(renderGuide,120)},()=>{guideStep=11;renderGuide()},()=>{guideStep=12;renderGuide()},startGuide];guideNext.onclick=actions[guideStep];if(voiceOn)speak(s.text)}
function clearSpotlights(){document.querySelectorAll('.spotlight').forEach(x=>x.classList.remove('spotlight'))}function speak(text){if(!voiceOn||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=.96;speechSynthesis.speak(u)}