-- Example artifact generated by ContextForge from DataHub-grounded context
with source as (
  select customer_id,
    email as primary_email,
    email as email, -- temporary compatibility alias
    customer_tier
  from {{ source('commerce', 'customers') }}
)
select * from source;
